In [1]:
import numpy as np

In [3]:
# numpy常用的矩阵一般有两种，array,matrix
mat_data=np.mat([[1,2],[3,4]])
mat_data

matrix([[1, 2],
        [3, 4]])

In [4]:
array_data=np.array([[1,2],[3,4]])
array_data

array([[1, 2],
       [3, 4]])

In [5]:
dan_data=np.eye(5)
dan_data

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])